[2024-06-15T15:02:24.192+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.raw_to_formatted_MAL scheduled__2024-06-14T02:15:00+00:00 [queued]>
[2024-06-15T15:02:24.200+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.raw_to_formatted_MAL scheduled__2024-06-14T02:15:00+00:00 [queued]>
[2024-06-15T15:02:24.200+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-15T15:02:24.212+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): raw_to_formatted_MAL> on 2024-06-14 02:15:00+00:00
[2024-06-15T15:02:24.218+0000] {standard_task_runner.py:57} INFO - Started process 5180 to run task
[2024-06-15T15:02:24.218+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:02:24.222+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'raw_to_formatted_MAL', 'scheduled__2024-06-14T02:15:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpw_58ed6w']
[2024-06-15T15:02:24.224+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask raw_to_formatted_MAL
[2024-06-15T15:02:24.277+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.raw_to_formatted_MAL scheduled__2024-06-14T02:15:00+00:00 [running]> on host 671934266c7c
[2024-06-15T15:02:24.351+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='raw_to_formatted_MAL' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T02:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-14T02:15:00+00:00'
[2024-06-15T15:02:24.402+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-15T15:02:24.411+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=raw_to_formatted_MAL, execution_date=20240614T021500, start_date=20240615T150224, end_date=20240615T150224
[2024-06-15T15:02:24.433+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-15T15:02:24.460+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-15T15:12:00.920+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.raw_to_formatted_MAL scheduled__2024-06-14T02:15:00+00:00 [queued]>
[2024-06-15T15:12:00.935+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.raw_to_formatted_MAL scheduled__2024-06-14T02:15:00+00:00 [queued]>
[2024-06-15T15:12:00.936+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-15T15:12:00.959+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): raw_to_formatted_MAL> on 2024-06-14 02:15:00+00:00
[2024-06-15T15:12:00.968+0000] {standard_task_runner.py:57} INFO - Started process 18947 to run task
[2024-06-15T15:12:00.968+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:12:00.973+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'raw_to_formatted_MAL', 'scheduled__2024-06-14T02:15:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpbyts22m1']
[2024-06-15T15:12:00.975+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask raw_to_formatted_MAL
[2024-06-15T15:12:01.038+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.raw_to_formatted_MAL scheduled__2024-06-14T02:15:00+00:00 [running]> on host 671934266c7c
[2024-06-15T15:12:01.127+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ivanmilos24@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='raw_to_formatted_MAL' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T02:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-14T02:15:00+00:00'
[2024-06-15T15:12:01.180+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-15T15:12:01.195+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=raw_to_formatted_MAL, execution_date=20240614T021500, start_date=20240615T151200, end_date=20240615T151201
[2024-06-15T15:12:01.224+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-15T15:12:01.227+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-06-15T15:12:01.229+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:12:01.230+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-06-15T15:12:01.236+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:12:01.264+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
