[2024-06-15T15:05:40.072+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.raw_to_formatted_ANI manual__2024-06-15T15:04:58.426510+00:00 [queued]>
[2024-06-15T15:05:40.091+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.raw_to_formatted_ANI manual__2024-06-15T15:04:58.426510+00:00 [queued]>
[2024-06-15T15:05:40.092+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-15T15:05:40.108+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): raw_to_formatted_ANI> on 2024-06-15 15:04:58.426510+00:00
[2024-06-15T15:05:40.117+0000] {standard_task_runner.py:57} INFO - Started process 7306 to run task
[2024-06-15T15:05:40.117+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:05:40.121+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'raw_to_formatted_ANI', 'manual__2024-06-15T15:04:58.426510+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpzj2a_702']
[2024-06-15T15:05:40.126+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask raw_to_formatted_ANI
[2024-06-15T15:05:40.189+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.raw_to_formatted_ANI manual__2024-06-15T15:04:58.426510+00:00 [running]> on host 671934266c7c
[2024-06-15T15:05:40.295+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ivanmilos24@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='raw_to_formatted_ANI' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T15:04:58.426510+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T15:04:58.426510+00:00'
[2024-06-15T15:05:40.355+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-15T15:05:40.366+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=raw_to_formatted_ANI, execution_date=20240615T150458, start_date=20240615T150540, end_date=20240615T150540
[2024-06-15T15:05:40.391+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-06-15T15:05:40.392+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:05:40.393+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-06-15T15:05:40.396+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T15:05:40.413+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-15T15:05:40.447+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
