[2024-06-15T14:38:53.535+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.index_to_elastic manual__2024-06-15T14:37:32.559640+00:00 [queued]>
[2024-06-15T14:38:53.543+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.index_to_elastic manual__2024-06-15T14:37:32.559640+00:00 [queued]>
[2024-06-15T14:38:53.544+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-15T14:38:53.555+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): index_to_elastic> on 2024-06-15 14:37:32.559640+00:00
[2024-06-15T14:38:53.563+0000] {standard_task_runner.py:57} INFO - Started process 3359 to run task
[2024-06-15T14:38:53.563+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T14:38:53.567+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'index_to_elastic', 'manual__2024-06-15T14:37:32.559640+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp1rldemlp']
[2024-06-15T14:38:53.569+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask index_to_elastic
[2024-06-15T14:38:53.608+0000] {task_command.py:415} INFO - Running <TaskInstance: main_dag.index_to_elastic manual__2024-06-15T14:37:32.559640+00:00 [running]> on host 671934266c7c
[2024-06-15T14:38:53.682+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='index_to_elastic' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T14:37:32.559640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T14:37:32.559640+00:00'
[2024-06-15T14:38:53.684+0000] {logging_mixin.py:151} INFO - Checking file: datalake/usage/animeAnalysis/AnimeTop300/20240615/combined_ratings.snappy.parquet
[2024-06-15T14:38:53.687+0000] {logging_mixin.py:151} INFO - File exists: True
[2024-06-15T14:38:53.690+0000] {logging_mixin.py:151} INFO - File readable: True
[2024-06-15T14:38:53.809+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-06-15T14:38:53.810+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T14:38:53.811+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-06-15T14:38:53.813+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-06-15T14:38:54.733+0000] {_transport.py:336} INFO - PUT https://my-first-deployment-3ab24b.es.us-central1.gcp.cloud.es.io:443/_bulk [status:200 duration:0.968s]
[2024-06-15T14:38:54.853+0000] {_transport.py:336} INFO - PUT https://my-first-deployment-3ab24b.es.us-central1.gcp.cloud.es.io:443/_bulk [status:200 duration:0.116s]
[2024-06-15T14:38:54.854+0000] {logging_mixin.py:151} INFO - Documents successfully indexed: 520
[2024-06-15T14:38:54.854+0000] {logging_mixin.py:151} INFO - Documents failed to index: 0
[2024-06-15T14:38:54.855+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-15T14:38:54.863+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=index_to_elastic, execution_date=20240615T143732, start_date=20240615T143853, end_date=20240615T143854
[2024-06-15T14:38:54.902+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-15T14:38:54.918+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
